// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"gpa/app/gpa/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/students/gpa",
				Handler: GpaHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"), rest.WithTimeout(60000*time.Millisecond),
	)
}
